---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: tinyauth
spec:
  name: Tinyauth
  callbackUrls:
    - "https://tinyauth.${SECRET_DOMAIN}/api/oauth/callback/pocketid"
  allowedUserGroups:
    - name: id-home
      namespace: security
  secret:
    keys:
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: OAUTH_CLIENT_ID
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: OAUTH_CLIENT_SECRET
