---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flohmarkt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: flohmarkt-secret
    template:
      data:
        # App
        ADMIN_PASSWORD: "{{ .FLOHMARKT_ADMIN_PASSWORD }}"
        SECRET_KEY: "{{ .FLOHMARKT_SECRET_KEY }}"
        SMTP_USER: "{{ .FLOHMARKT_SMTP_USER }}"
        SMTP_PASSWORD: "{{ .FLOHMARKT_SMTP_PASSWORD }}"
  dataFrom:
    - extract:
        key: flohmarkt
