---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flohmarkt
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      flohmarkt:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/drag0n141/flohmarkt
              tag: latest@sha256:44d10d8187f3fecfa2e076928b4d2ac10fa7adce29309090e0af67a18e06b2e0
            env:
              TZ: Europe/Berlin
              NUM_TABLES: 40
              PAYMENT_METHODS: sepa
              PRICE_STANDARD: 15.00
              PRICE_INTERNAL: 10.00
              CURRENCY: EUR
              DB_PATH: /data/flohmarkt.db
              SMTP_HOST: smtp.strato.de
              SMTP_PORT: 587
              SMTP_USE_TLS: true
            envFrom:
              - secretRef:
                  name: flohmarkt-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 8000
    route:
      app:
        hostnames:
          - "flohmarkt.${SECRET_DOMAIN_SHORT}"
        parentRefs:
          - name: envoy-external
            namespace: networking
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          flohmarkt:
            app:
              - path: /data
                subPath: data
              - path: /app/static/uploads
                subPath: uploads
      tmpfs:
        type: emptyDir
        advancedMounts:
          flohmarkt:
            app:
              - path: /tmp
                subPath: tmp
