---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  disableDefaultAdminSecret: true
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "true"
    auth.anonymous:
      enabled: "false"
    auth.generic_oauth:
      enabled: "true"
      name: "Pocket ID"
      allow_sign_up: "true"
      scopes: "openid profile email groups"
      auth_url: "https://id.${SECRET_DOMAIN}/authorize"
      token_url: "https://id.${SECRET_DOMAIN}/api/oidc/token"
      api_url: "https://id.${SECRET_DOMAIN}/api/oidc/userinfo"
      role_attribute_path: "contains(groups[*], 'ID-Admin') && 'Admin' || 'Viewer'"
    database:
      type: "postgres"
    log:
      mode: console
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    security:
      angular_support_enabled: "true"
    server:
      enable_gzip: "true"
      root_url: https://grafana.${SECRET_DOMAIN_INTERNAL}
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          initContainers:
            - name: init-db
              image: ghcr.io/home-operations/postgres-init:18
              envFrom:
                - secretRef:
                    name: grafana-secret
          containers:
            - name: grafana
              envFrom:
                - secretRef:
                    name: grafana-secret
                - secretRef:
                    name: grafana-oidc-credentials
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: { drop: ["ALL"] }
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
  httpRoute:
    spec:
      hostnames:
        - grafana.${SECRET_DOMAIN_INTERNAL}
      parentRefs:
        - name: envoy-internal
          namespace: networking
