---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  disableDefaultAdminSecret: true
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "false"
    auth.anonymous:
      enabled: "false"
    log:
      mode: console
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    security:
      angular_support_enabled: "true"
    server:
      enable_gzip: "true"
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          initContainers:
            - name: init-db
              image: ghcr.io/home-operations/postgres-init:18
              envFrom:
                - secretRef:
                    name: grafana-secret
                - secretRef:
                    name: grafana-oidc-credentials
          containers:
            - name: grafana
              envFrom:
                - secretRef:
                    name: grafana-secret
                - secretRef:
                    name: grafana-oidc-credentials
              env:
                - name: GF_AUTH_BASIC_ENABLED
                  value: "false"
                - name: GF_AUTH_GENERIC_OAUTH_ENABLED
                  value: "true"
                - name: GF_AUTH_GENERIC_OAUTH_API_URL
                  value: https://id.${SECRET_DOMAIN}/api/oidc/userinfo
                - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
                  value: https://id.${SECRET_DOMAIN}/authorize
                - name: GF_AUTH_GENERIC_OAUTH_EMPTY_SCOPES
                  value: "false"
                - name: GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
                  value: "contains(groups[*], 'ID-Admin') && 'Admin' || 'Viewer'"
                - name: GF_AUTH_GENERIC_OAUTH_SCOPES
                  value: openid profile email groups
                - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
                  value: https://id.${SECRET_DOMAIN}/api/oidc/token
                - name: GF_AUTH_OAUTH_AUTO_LOGIN
                  value: "true"
                - name: GF_DATABASE_TYPE
                  value: postgres
                - name: GF_EXPLORE_ENABLED
                  value: "true"
                - name: GF_SERVER_ROOT_URL
                  value: https://grafana.${SECRET_DOMAIN_INTERNAL}
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: { drop: ["ALL"] }
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
  httpRoute:
    spec:
      hostnames:
        - grafana.${SECRET_DOMAIN_INTERNAL}
      parentRefs:
        - name: envoy-internal
          namespace: networking
