---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./pocketidoidcclient.yaml
  - ./grafana.yaml
  - ./dashboards-misc.yaml
  - ./dashboards-flux.yaml
  - ./dashboards-networking.yaml
  - ./dashboards-unifi.yaml
  - ./dashboards-postgres.yaml
