---
services:
  traefik:
    image: 'docker.io/traefik:3.6.10'
    hostname: 'traefik'
    container_name: 'traefik'
    restart: 'always'
    cap_drop:
      - 'ALL'
    command:
      - '--configFile=/etc/traefik/traefik_config.yml'
    ports:
      - '80:80'
      - '443:443/tcp'
      - '443:443/udp'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/mnt/nvme/appdata/traefik/certs:/letsencrypt:rw'
      - '/mnt/nvme/appdata/traefik/logs:/var/log/traefik:rw'
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik_config.yml
      - source: traefik_dynamic_config
        target: /etc/traefik/dynamic_config.yml
    environment:
      - 'CF_API_EMAIL=${CLOUDFLARE_EMAIL}'
      - 'CF_DNS_API_TOKEN=${CLOUDFLARE_TRAEFIK_API_TOKEN}'
      - 'TZ=${TZ}'
    networks:
      - traefik
    security_opt:
      - 'no-new-privileges:true'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik-rtr.entrypoints=https'
      - 'traefik.http.routers.traefik-rtr.rule=Host(`traefik-nas01.${DOMAIN_INT}`)'
      - 'traefik.http.routers.traefik-rtr.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.traefik-rtr.middlewares=chain-internal-tinyauth@file'
      - 'traefik.http.routers.traefik-rtr.service=api@internal'
      - 'traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.${DOMAIN_INT}'
    deploy:
      resources:
        limits:
          memory: 2048M

networks:
  traefik:
    name: traefik
    external: true
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.1.0/24
         gateway: 172.16.1.1

configs:
  traefik_config:
    content: |-
      ---
      api:
        insecure: false
        dashboard: true

      ping:
        entryPoint: "ping"

      global:
        sendAnonymousUsage: false
        checkNewVersion: true

      providers:
        docker:
          endpoint: "unix:///var/run/docker.sock"
          exposedByDefault: false
          network: traefik
        file:
          filename: "/etc/traefik/dynamic_config.yml"

      log:
        level: "INFO"
        format: "common"
        maxSize: 100
        maxBackups: 3
        maxAge: 3
        compress: true

      accessLog:
        filePath: /var/log/traefik/access.log
        bufferingSize: 100
        filters:
          minDuration: 100ms
          retryAttempts: true
          statusCodes:
            - 200-299
            - 400-499
            - 500-599
        format: json
        fields:
          defaultMode: drop
          names:
            ClientAddr: keep
            ClientHost: keep
            DownstreamContentSize: keep
            DownstreamStatus: keep
            Duration: keep
            RequestMethod: keep
            RequestPath: keep
            RequestProtocol: keep
            RetryAttempts: keep
            ServiceName: keep
            StartUTC: keep
            TLSCipher: keep
            TLSVersion: keep
          headers:
            defaultMode: drop
            names:
              Authorization: redact
              Content-Type: keep
              Cookie: redact
              User-Agent: keep
              X-Forwarded-For: keep
              X-Forwarded-Proto: keep
              X-Real-Ip: keep

      entryPoints:
        ping:
          address: "localhost:8082"
        http:
          address: ":80"
          http:
            redirections:
              entryPoint:
                to: https
                scheme: https
        https:
          address: ":443"
          transport:
            respondingTimeouts:
              readTimeout: "30m"
          http3:
            advertisedPort: 443
          http:
            tls:
              certResolver: letsencrypt
              domains:
                - main: "*.${DOMAIN}"
            middlewares:
              - chain-no-auth@file
            encodedCharacters:
              allowEncodedSlash: true
              allowEncodedQuestionMark: true

      certificatesResolvers:
        letsencrypt:
          acme:
            storage: "/letsencrypt/acme.json"
            dnsChallenge:
              provider: cloudflare
              resolvers:
                - "1.1.1.1:53"
                - "1.0.0.1:53"
              propagation:
                delayBeforeChecks: 60

      serversTransport:
        insecureSkipVerify: true

  traefik_dynamic_config:
    content: |-
      ---
      tls:
        options:
          default:
            minVersion: VersionTLS12
            cipherSuites:
              - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
              - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
              - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
              - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
              - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
              - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
          modern-2020:
            minVersion: VersionTLS13

      http:
        middlewares:
          middlewares-rate-limit:
            rateLimit:
              average: 100
              burst: 50

          middlewares-secure-headers:
            headers:
              accessControlAllowMethods:
                - GET
                - OPTIONS
                - PUT
                - POST
              accessControlMaxAge: 100
              hostsProxyHeaders:
                - X-Forwarded-Host
              stsSeconds: 31536000
              stsIncludeSubdomains: false
              stsPreload: true
              forceSTSHeader: true
              customFrameOptionsValue: "allow-from https:${DOMAIN}"
              contentTypeNosniff: true
              browserXssFilter: true
              frameDeny: true
              referrerPolicy: same-origin
              customResponseHeaders:
                Permissions-Policy: "accelerometer=(),camera=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),payment=(),usb=()"
                Content-Security-Policy: "upgrade-insecure-requests;"
                X-Frame-Options: SAMEORIGIN
                X-Robots-Tag: "none,noindex,nofollow,noarchive,nosnippet,notranslate,noimageindex"
                X-Permitted-Cross-Domain-Policies: none
                X-Forwarded-Proto: https
                X-Powered-By: ""
                server: ""

          middlewares-secure-headers-garage:
            headers:
              accessControlAllowMethods:
                - GET
                - HEAD
                - POST
                - PUT
                - DELETE
              accessControlMaxAge: 3000
              accessControlAllowOriginList:
                - "*"
              accessControlAllowHeaders:
                - "*"
              addVaryHeader: true

          middlewares-compress:
            compress:
              minResponseBodyBytes: 1024
              excludedContentTypes:
                - application/zip
                - application/octet-stream

          middlewares-tinyauth:
            forwardAuth:
              address: "https://tinyauth.${DOMAIN}/api/auth/traefik"
              trustForwardHeader: true
              authResponseHeaders:
                - Remote-User
                - Remote-Groups
                - Remote-Name
                - Remote-Email

          middlewares-only-local:
            ipAllowList:
              sourceRange:
                - 192.168.40.0/24
                - 192.168.41.0/24
                - 192.168.42.0/24
                - 192.168.140.0/24
                - 192.168.230.0/24
                - 192.168.240.0/24
                - 192.168.254.0/24
                - 172.18.0.0/16

          chain-no-auth:
            chain:
              middlewares:
                - middlewares-rate-limit
                - middlewares-secure-headers
                - middlewares-compress

          chain-tinyauth:
            chain:
              middlewares:
                - middlewares-rate-limit
                - middlewares-secure-headers
                - middlewares-compress
                - middlewares-tinyauth

          chain-garage:
            chain:
              middlewares:
                - middlewares-secure-headers-garage

          chain-internal-no-auth:
            chain:
              middlewares:
                - middlewares-only-local
                - middlewares-secure-headers
                - middlewares-compress

          chain-internal-tinyauth:
            chain:
              middlewares:
                - middlewares-only-local
                - middlewares-secure-headers
                - middlewares-compress
                - middlewares-tinyauth
