---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 3
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:184219ecec559d15fa03932b0d3005e0372f7027746bb682aca478bc4918f776
  primaryUpdateStrategy: unsupervised
  storage:
    size: 15Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 512MB
    extensions:
      - name: postgis
        image:
          # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgis-extension
          reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.3-18-trixie
        ld_library_path:
          - system
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      hugepages-2Mi: 2Gi
      memory: 3Gi
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters: &parameters
        barmanObjectName: garage
        serverName: postgres
  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters: *parameters
#    - name: &oldCluster postgres17
#      connectionParameters:
#        host: postgres17-rw.database.svc.cluster.local
#        user: postgres
#        dbname: postgres
#        sslmode: require
#      password:
#        name: cloudnative-pg-secret
#        key: password
#  bootstrap:
#    recovery:
#      source: source
#    initdb:
#      import:
#        type: monolith
#        databases: ["*"]
#        roles: ["*"]
#        source:
#          externalCluster: *oldCluster
