---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: miniflux
spec:
  name: Miniflux
  callbackUrls:
    - "https://miniflux.${SECRET_DOMAIN}/oauth2/oidc/callback"
  allowedUserGroups:
    - name: id-rss
      namespace: security
  secret:
    keys:
      clientID: OAUTH2_CLIENT_ID
      clientSecret: OAUTH2_CLIENT_SECRET
