---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./pocketidoidcclient.yaml
configMapGenerator:
  - name: netbox-sso-configmap
    files:
      - sso_pipeline_roles.py=./resources/sso_pipeline_roles.py
generatorOptions:
  disableNameSuffixHash: true
