---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tubearchivist
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tubearchivist-secret
    template:
      data:
        # App
        TA_USERNAME: "{{ .TA_USERNAME }}"
        TA_PASSWORD: "{{ .TA_PASSWORD }}"
        ELASTIC_PASSWORD: "{{ .TA_ELASTIC_PASSWORD }}"
        REDIS_URL: |-
          redis://:{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379/16
  dataFrom:
    - extract:
        key: dragonfly
    - extract:
        key: tubearchivist
