---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      wg-easy:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/wg-easy/wg-easy
              tag: 15.4.0@sha256:0e7bc9d34e86ddcaa92bc700d4d7dc9b33291dbc07ac8d13382f7c2095f949ec
            env:
              TZ: Europe/Berlin
              PORT: &port 80
              DISABLE_IPV6: true
              EXPERIMENTAL_AWG: true
              DISABLE_VERSION_CHECK: true
              INIT_ENABLED: true
              INIT_HOST: vpn.${SECRET_DOMAIN}
              INIT_PORT: 51820
              INIT_DNS: 192.168.254.1
              INIT_IPV4_CIDR: 192.168.45.0/24
              OAUTH_PROVIDERS: oidc
              OAUTH_AUTO_REGISTER: true
              OAUTH_OIDC_SERVER: https://id.${SECRET_DOMAIN}
              OAUTH_OIDC_NAME: "Pocket ID"
            envFrom:
              - secretRef:
                  name: wg-easy-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { add: ["NET_ADMIN", "NET_RAW"], drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 256Mi
          wstunnel:
            image:
              repository: ghcr.io/erebe/wstunnel
              tag: v10.6.2@sha256:bfb751827e4222366c6068452d578ea0bcad7d88c93a5c98fb665402a4b349b3
            command: ["/bin/sh", "-c", "exec /home/app/wstunnel server wss://0.0.0.0:8080 --restrict-to=localhost:51820"]
            env:
              TZ: Europe/Berlin
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 256Mi
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        primary: true
        ports:
          http:
            port: *port
      wstunnel:
        ports:
          http:
            appProtocol: kubernetes.io/wss
            port: 8080
      wireguard:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "wg.${SECRET_DOMAIN_INTERNAL}"
          lbipam.cilium.io/ips: 192.168.222.240
        ports:
          wg:
            port: 51820
            protocol: UDP
    route:
      app:
        forceRename: "{{ .Release.Name }}"
        hostnames:
          - "wireguard.${SECRET_DOMAIN_INTERNAL}"
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - identifier: app
                port: http
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /etc/wireguard
      tmpfs:
        type: emptyDir
        advancedMounts:
          wg-easy:
            app:
              - path: /run
                subPath: run
              - path: /tmp
                subPath: tmp
