---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plex-mcp-secret
    template:
      data:
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        PLEX_URL: "{{ .PLEX_URL }}"
  dataFrom:
    - extract:
        key: plex
