---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: n8n-secret
    template:
      data:
        # App
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
        CHECKMK_USER: "{{ .NVD_API_KEY }}"
        CHECKMK_PASSWORD: "{{ .CHECKMK_PASSWORD }}"
        GOTIFY_TOKEN: "{{ .GOTIFY_TOKEN_CVE }}"
        # API
        MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
        NVD_API_KEY: "{{ .NVD_API_KEY }}"
        # Database
        DB_POSTGRESDB_HOST: &dbhost "postgres-rw.database.svc.cluster.local"
        DB_POSTGRESDB_PORT: "5432"
        DB_POSTGRESDB_USER: &dbuser "{{ .N8N_POSTGRES_USER }}"
        DB_POSTGRESDB_PASSWORD: &dbpass "{{ .N8N_POSTGRES_PASSWORD }}"
        DB_POSTGRESDB_DATABASE:  &dbname "{{ .N8N_POSTGRES_DB }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: checkmk
    - extract:
        key: cloudnative-pg
    - extract:
        key: gotify
    - extract:
        key: minimax
    - extract:
        key: n8n
    - extract:
        key: nvd
