---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-unifi
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-dns-unifi
  values:
    fullnameOverride: *app
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/home-operations/external-dns-unifi-webhook
          tag: 0.10.2@sha256:1f51f841e217d8bc6481655481ce82e0f0be70ad359c23d7d866d53a51d87fa9
        env:
          - name: UNIFI_HOST
            value: https://192.168.1.1
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: &secret external-dns-unifi-secret
                key: UNIFI_API_KEY
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    extraArgs:
      - --annotation-filter=external-dns.alpha.kubernetes.io/exclude-unifi notin (true)
    triggerLoopOnEvent: true
    policy: sync
    sources: ["gateway-httproute", "service"]
    txtOwnerId: main
    txtPrefix: k8s.main.
    excludeDomains: ["ipv4.${SECRET_DOMAIN}"]
    domainFilters: ["${SECRET_DOMAIN}", "${SECRET_DOMAIN_INTERNAL}", "${SECRET_DOMAIN_SHORT}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    resources:
      requests:
        cpu: 16m
        memory: 90M
      limits:
        memory: 90M
