---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: pangolin
spec:
  endpoints:
    - dnsName: "pangolin.${SECRET_DOMAIN}"
      recordType: A
      targets: ["${SECRET_PANGOLIN_IP}"]
    - dnsName: "external.${SECRET_DOMAIN}"
      recordType: A
      targets: ["${SECRET_PANGOLIN_IP}"]
