---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: newt-secret
    creationPolicy: Owner
    template:
      data:
        NEWT_ID: "{{ .PANGOLIN_NEWT_ID }}"
        NEWT_SECRET: "{{ .PANGOLIN_NEWT_SECRET }}"
  dataFrom:
    - extract:
        key: pangolin
