---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piper
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      piper:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mirror.gcr.io/rhasspy/wyoming-piper
              tag: 2.5.2@sha256:7d39aafac409c2b6b09d999ed04d84c311d632e558b35baa60fad6aac722af7a
            args:
              - --voice
              - de_DE-thorsten-medium
            env:
              TZ: Europe/Berlin
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: LoadBalancer
        annotations:
          external-dns.kubernetes.io/hostname: "piper.${SECRET_DOMAIN_INTERNAL}"
          lbipam.cilium.io/ips: 192.168.222.132
        ports:
          http:
            port: 10200
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data
      tmpfs:
        type: emptyDir
        medium: Memory
        advancedMounts:
          piper:
            app:
              - path: /tmp
                subPath: tmp
