---
name: pangolin
services:
  pangolin:
    image: ghcr.io/fosrl/pangolin:ee-1.17.1
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - /opt/appdata/pangolin/config:/app/config:rw
    configs:
      - source: pangolin_config
        target: /app/config/config.yml
    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "-f"
        - "http://localhost:3001/api/v1/"
      interval: "10s"
      timeout: "10s"
      retries: 15
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 256m

  gerbil:
    image: ghcr.io/fosrl/gerbil:1.3.1
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3004
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    volumes:
      - /opt/appdata/pangolin/config/:/var/config:rw
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 21820:21820/udp
      - 443:443
      - 80:80
      - 22000:22000
      - 22000:22000/udp
      - 21027:21027/udp
      - 10011:10011
      - 30033:30033
      - 9987:9987/udp

  traefik:
    image: docker.io/traefik:v3.6.14
    container_name: traefik
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_DNS_API_TOKEN=${CLOUDFLARE_TRAEFIK_API_TOKEN}
      - TZ=${TZ}
    network_mode: service:gerbil
    depends_on:
      pangolin:
        condition: service_healthy
    volumes:
      - /opt/appdata/pangolin/config/letsencrypt:/letsencrypt:rw
      - /opt/appdata/pangolin/config/traefik/logs:/var/log/traefik:rw
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik_config.yml
      - source: traefik_dynamic_config
        target: /etc/traefik/dynamic_config.yml
    security_opt:
      - 'no-new-privileges:true'

  geoipupdate:
    container_name: geoipupdate
    image: ghcr.io/maxmind/geoipupdate:v7.1.1
    restart: unless-stopped
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${MAXMIND_ACCOUNT_ID}
      - GEOIPUPDATE_LICENSE_KEY=${MAXMIND_PANGOLIN_LICENSE_KEY}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country GeoLite2-ASN
      - GEOIPUPDATE_FREQUENCY=72
    volumes:
      - /opt/appdata/pangolin/config/GeoLite2:/usr/share/GeoIP:rw
    security_opt:
      - 'no-new-privileges:true'

networks:
  default:
    driver: bridge
    name: pangolin

configs:
  pangolin_config:
    content: |-
      # https://docs.pangolin.net/
      gerbil:
          start_port: 51820
          base_endpoint: "pangolin.${DOMAIN}"
      app:
          dashboard_url: "https://pangolin.${DOMAIN}"
          log_level: "info"
          telemetry:
              anonymous_usage: false
      domains:
          domain1:
              base_domain: "${DOMAIN}"
              prefer_wildcard_cert: true
              cert_resolver: "letsencrypt"
          domain2:
              base_domain: "${DOMAIN_SHORT}"
              prefer_wildcard_cert: true
              cert_resolver: "letsencrypt"
          domain3:
              base_domain: "${DOMAIN_PANGOLIN}"
              prefer_wildcard_cert: true
              cert_resolver: "letsencrypt"
      server:
          secret: "${PANGOLIN_SERVER_SECRET}"
          cors:
              origins: ["https://pangolin.${DOMAIN}"]
              methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
              allowed_headers: ["X-CSRF-Token", "Content-Type"]
              credentials: false
          maxmind_db_path: "/app/config/GeoLite2/GeoLite2-Country.mmdb"
          maxmind_asn_path: "/app/config/GeoLite2/GeoLite2-ASN.mmdb"
      flags:
          require_email_verification: false
          disable_signup_without_invite: true
          disable_user_create_org: false
          allow_raw_resources: true
          enable_integration_api: true
  traefik_config:
    content: |-
      ---
      api:
        insecure: true
        dashboard: true

      providers:
        http:
          endpoint: "http://pangolin:3001/api/v1/traefik-config"
          pollInterval: "5s"
        file:
          filename: "/etc/traefik/dynamic_config.yml"

      experimental:
        plugins:
          badger:
            moduleName: "github.com/fosrl/badger"
            version: "v1.3.1"

      log:
        level: "INFO"
        format: "common"
        maxSize: 100
        maxBackups: 3
        maxAge: 3
        compress: true

      accessLog:
        bufferingSize: 100
        fields:
          defaultMode: drop
          headers:
            defaultMode: drop
            names:
              Authorization: redact
              Content-Type: keep
              Cookie: redact
              User-Agent: keep
              X-Forwarded-For: keep
              X-Forwarded-Proto: keep
              X-Real-Ip: keep
          names:
            ClientAddr: keep
            ClientHost: keep
            DownstreamContentSize: keep
            DownstreamStatus: keep
            Duration: keep
            RequestMethod: keep
            RequestPath: keep
            RequestProtocol: keep
            RetryAttempts: keep
            ServiceName: keep
            StartUTC: keep
            TLSCipher: keep
            TLSVersion: keep
        filePath: /var/log/traefik/access.log
        filters:
          minDuration: 100ms
          retryAttempts: true
          statusCodes:
            - 200-299
            - 400-499
            - 500-599
        format: json

      certificatesResolvers:
        letsencrypt:
          acme:
            storage: "/letsencrypt/acme.json"
            dnsChallenge:
              provider: cloudflare
              resolvers:
                - "1.1.1.1:53"
                - "1.0.0.1:53"
              propagation:
                delayBeforeChecks: 60

      entryPoints:
        web:
          address: ":80"
        websecure:
          address: ":443"
          transport:
            respondingTimeouts:
              readTimeout: "30m"
          http:
            tls:
              certResolver: "letsencrypt"
            encodedCharacters:
              allowEncodedSlash: true
              allowEncodedQuestionMark: true
        tcp-22000:
          address: ":22000/tcp"
        tcp-10011:
          address: ":10011/tcp"
        tcp-30033:
          address: ":30033/tcp"
        udp-9987:
          address: ":9987/udp"
        udp-21027:
          address: ":21027/udp"
        udp-22000:
          address: ":22000/udp"

      serversTransport:
        insecureSkipVerify: true

      ping:
        entryPoint: "web"

  traefik_dynamic_config:
    content: |-
      ---
      http:
        middlewares:
          default-whitelist:
            ipWhiteList:
              sourceRange:
                - 10.0.0.0/8
                - 192.168.0.0/16
                - 172.16.0.0/12
          redirect-to-https:
            redirectScheme:
              scheme: https
          security-headers:
            headers:
              contentTypeNosniff: true
              customFrameOptionsValue: SAMEORIGIN
              customResponseHeaders:
                Content-Security-Policy: upgrade-insecure-requests;
                Permissions-Policy: "accelerometer=(),camera=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),payment=(),usb=()"
                Server: ""
                X-Forwarded-Proto: https
                X-Powered-By: ""
              forceSTSHeader: true
              hostsProxyHeaders:
                - X-Forwarded-Host
              referrerPolicy: strict-origin-when-cross-origin
              sslProxyHeaders:
                X-Forwarded-Proto: https
              stsIncludeSubdomains: false
              stsPreload: true
              stsSeconds: 63072000
        routers:
          # HTTP to HTTPS redirect router
          main-app-router-redirect:
            rule: "Host(`pangolin.${DOMAIN}`)"
            service: next-service
            entryPoints:
              - web
            middlewares:
              - redirect-to-https

          # Next.js router (handles everything except API and WebSocket paths)
          next-router:
            rule: "Host(`pangolin.${DOMAIN}`) && !PathPrefix(`/api/v1`)"
            service: next-service
            entryPoints:
              - websecure
            middlewares:
              - security-headers
            tls:
              certResolver: letsencrypt
              domains:
                - main: "${DOMAIN}"
                  sans:
                    - "*.${DOMAIN}"
                - main: "${DOMAIN_SHORT}"
                  sans:
                    - "*.${DOMAIN_SHORT}"

          # API router (handles /api/v1 paths)
          api-router:
            rule: "Host(`pangolin.${DOMAIN}`) && PathPrefix(`/api/v1`)"
            service: api-service
            entryPoints:
              - websecure
            middlewares:
              - security-headers
            tls:
              certResolver: letsencrypt
          int-api-router:
            rule: "Host(`pangolin-api.${DOMAIN}`)"
            service: int-api-service
            entryPoints:
              - websecure
            tls:
              certResolver: letsencrypt

          # WebSocket router
          ws-router:
            rule: "Host(`pangolin.${DOMAIN}`)"
            service: api-service
            entryPoints:
              - websecure
            middlewares:
              - security-headers
            tls:
              certResolver: letsencrypt

        services:
          next-service:
            loadBalancer:
              servers:
                - url: "http://pangolin:3002"

          api-service:
            loadBalancer:
              servers:
                - url: "http://pangolin:3000"

          int-api-service:
            loadBalancer:
              servers:
                - url: "http://pangolin:3003"
