---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify-icons
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gotify-icons-secret
    template:
      data:
        GOTIFY_USERNAME : "{{ .GOTIFY_DEFAULTUSER_NAME }}"
        GOTIFY_PASSWORD: "{{ .GOTIFY_DEFAULTUSER_PASS }}"
  dataFrom:
    - extract:
        key: gotify
