---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gotify-icons
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      gotify-icons:
        type: cronjob
        cronjob:
          schedule: "@daily"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        initContainers:
          pip-install:
            image:
              repository: public.ecr.aws/docker/library/python
              tag: 3.14-slim@sha256:8e4071294d046d45b31a902e02a8560a45c351898513b66ec659ca39fd30d170
            command:
              - pip
              - install
              - "--target=/pip-packages"
              - "requests"
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/python
              tag: 3.14-slim@sha256:8e4071294d046d45b31a902e02a8560a45c351898513b66ec659ca39fd30d170
            command: ["python", "/scripts/gotify-icons.py"]
            env:
              TZ: Europe/Berlin
              GOTIFY_URL: http://gotify.default.svc.cluster.local
              PYTHONPATH: /pip-packages
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      script:
        type: configMap
        name: "{{ .Release.Name }}-scripts"
        globalMounts:
          - path: /scripts/gotify-icons.py
            subPath: gotify-icons.py
            readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          gotify-icons:
            app:
              - path: /pip-packages
                subPath: pip-packages
              - path: /tmp
                subPath: tmp
            pip-install:
              - path: /pip-packages
                subPath: pip-packages
              - path: /tmp
                subPath: tmp-pip
