---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dex-secret
    template:
      data:
        # OIDC
        MCP_DEX_OAUTH_CLIENT_ID: "{{ .MCP_DEX_CLIENT_ID }}"
        MCP_DEX_OAUTH_CLIENT_SECRET: "{{ .MCP_DEX_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: pocket-id
