---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: nextcloud
  values:
    deploymentLabels:
      nfsMount: "true"
      postgres: "true"
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    nextcloud:
      host: &host nextcloud.${SECRET_DOMAIN}
      extraInitContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:18
          envFrom:
            - secretRef:
                name: &secret nextcloud-secret
      extraVolumes:
      - name: nfs-home
        nfs:
          server: "nas01.${SECRET_DOMAIN_INT}"
          path: "/mnt/data/home"
      extraVolumeMounts:
      - name: nfs-home
        mountPath: "/mnt/data/home"
      extraEnv:
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: &secretoidc nextcloud-oidc-credentials
              key: client_id
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: *secretoidc
              key: client_secret
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: *secret
              key: REDIS_PASSWORD
      hooks:
        post-upgrade: |
          cd /var/www/html
          ./occ upgrade
          ./occ db:add-missing-indices

        before-starting: |
          #!/bin/bash
          set -exu # Remove the -u if you encounter issues booting

          cd /var/www/html

          # Upgrade
          ./occ upgrade                                || /bin/true
          ./occ maintenance:mode --off                 || /bin/true
          ./occ app:update --all                       || /bin/true
          ./occ db:add-missing-indices                 || /bin/true
          ./occ maintenance:repair --include-expensive || /bin/true

          # SSO
          test -d custom_apps/user_oidc ||  ./occ app:install user_oidc
          ./occ user_oidc:provider sso \
            --clientid="$${OIDC_CLIENT_ID}" \
            --clientsecret="$${OIDC_CLIENT_SECRET}" \
            --discoveryuri="https://id.${SECRET_DOMAIN}/.well-known/openid-configuration" \
            --unique-uid=0 \
            --group-provisioning=1 \
            --group-whitelist-regex='^ID-Nextcloud$' \
            --group-restrict-login-to-whitelist=1 \
            --mapping-uid=preferred_username \
            --mapping-email=email \
            --mapping-display-name=name \
            --mapping-groups=groups \
            --mapping-quota=quota
          ./occ config:app:set --value=0 user_oidc allow_multiple_user_backends # Only login with SSO

      existingSecret:
        enabled: true
        secretName: *secret
        usernameKey: ADMIN_USER
        passwordKey: ADMIN_PASS
        smtpHostKey: SMTP_HOST
        smtpUsernameKey: SMTP_USERNAME
        smtpPasswordKey: SMTP_PASSWORD
      mail:
        enabled: true
        fromAddress: nextcloud
        domain: ${SECRET_DOMAIN}
        smtp:
          port: 2525
          secure: NONE
          authtype: NONE
      defaultConfigs:
        redis.config.php: false
      configs:
        local.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' =>
            array (
              0 => '127.0.0.1',
              1 => '10.42.0.0/16',
              2 => '10.43.0.0/16',
            ),
            'forwarded_for_headers' =>
            array (
              0 => 'HTTP_X_FORWARDED_FOR',
            ),
            'default_phone_region' => 'DE',
            'overwrite.cli.url' => 'https://nextcloud.${SECRET_DOMAIN}',
            'overwriteprotocol' => 'https',
            'quota_include_external_storage' => 'false',
            'skeletondirectory' => '',
            'knowledgebaseenabled' => 'false',
            'maintenance_window_start' => '1',
            'enable_previews' => false,
            'trashbin_retention_obligation' => 'auto, 30',
            'auth.bruteforce.protection.enabled' => true,
          );
        redis.config.php: |-
          <?php
          $CONFIG = array(
            'memcache.distributed' => '\OC\Memcache\Redis',
            'memcache.locking' => '\OC\Memcache\Redis',
            'redis' => array(
              'host' => 'dragonfly.database.svc.cluster.local',
              'port' => getenv('REDIS_PORT') ?: 6379,
              'dbindex' => getenv('REDIS_DATABASE') ?: 10,
              'password' => getenv('REDIS_PASSWORD'),
            ),
          );
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
        www.conf: |
          [www]
          user = www-data
          group = www-data
          listen = 127.0.0.1:9000
          pm = dynamic
          pm.max_children = 57
          pm.start_servers = 14
          pm.min_spare_servers = 14
          pm.max_spare_servers = 42
          pm.max_requests = 500
          pm.process_idle_timeout = 10s
    cronjob:
      enabled: true
      type: cronjob
      cronjob:
        successfulJobsHistoryLimit: 1
        securityContext:
          runAsGroup: 33
          runAsNonRoot: true
          runAsUser: 33
        affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - nextcloud
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - app
                topologyKey: kubernetes.io/hostname
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: *secret
        usernameKey: POSTGRES_USER
        passwordKey: POSTGRES_PASSWORD
        hostKey: POSTGRES_HOST
        databaseKey: POSTGRES_DB
    persistence:
      enabled: true
      existingClaim: *app
    httpRoute:
      enabled: true
      hostnames:
        - *host
      parentRefs:
        - name: envoy-external
          namespace: networking
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: "/"
