---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: nextcloud
spec:
  name: Nextcloud
  callbackUrls:
    - "https://nextcloud.${SECRET_DOMAIN}/apps/oidc_login/oidc"
  allowedUserGroups:
    - name: id-nextcloud
      namespace: security
