---
services:
  llama-cpp:
    image: 'ghcr.io/ggml-org/llama.cpp:server-cuda-b9776'
    hostname: 'llama-cpp'
    container_name: 'llama-cpp'
    restart: 'always'
    runtime: nvidia
    read_only: true
    volumes:
      - '/mnt/nvme/appdata/llm/models:/models:rw'
      - '/mnt/nvme/appdata/llm/cache:/root/.cache:rw'
    tmpfs:
      - '/tmp'
    environment:
      - 'TZ=${TZ}'
      - 'NVIDIA_VISIBLE_DEVICES=all'
      - 'NVIDIA_DRIVER_CAPABILITIES=compute,utility'
      - 'GGML_CUDA_FORCE_MMQ=1'
      - 'LLAMA_ARG_HF_REPO=unsloth/Qwen3.5-4B-GGUF'
      - 'LLAMA_ARG_HF_FILE=Qwen3.5-4B-Q4_K_M.gguf'
      - 'LLAMA_ARG_MODEL=/models/Qwen3.5-4B-Q4_K_M.gguf'
      - 'LLAMA_ARG_MMPROJ_URL=https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/mmproj-BF16.gguf'
      - 'LLAMA_ARG_HOST=0.0.0.0'
      - 'LLAMA_ARG_PORT=8080'
      - 'LLAMA_ARG_N_GPUS=1'
      - 'LLAMA_ARG_GPU_LAYERS=99'
      - 'LLAMA_ARG_JINJA=1'
      - 'LLAMA_ARG_API_KEY=${LLAMA_API_KEY}'
      - 'LLAMA_ARG_CHAT_TEMPLATE_KWARGS={"enable_thinking":false}'
      - 'LLAMA_ARG_NO_WEBUI=1'
      - 'LLAMA_ARG_REASONING=off'
      - 'LLAMA_ARG_REASONING_BUDGET=0'
      - 'LLAMA_ARG_CTX_SIZE=8192'
    networks:
      - traefik
    security_opt:
      - 'no-new-privileges:true'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.llama-webui-rtr.entrypoints=https'
      - 'traefik.http.routers.llama-webui-rtr.rule=Host(`llama.${DOMAIN_INT}`)'
      - 'traefik.http.routers.llama-webui-rtr.tls=true'
      - 'traefik.http.routers.llama-webui-rtr.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.llama-webui-rtr.middlewares=chain-internal-no-auth@file'
      - 'traefik.http.routers.llama-webui-rtr.service=llama-webui-svc'
      - 'traefik.http.services.llama-webui-svc.loadbalancer.server.port=8080'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  traefik:
    name: traefik
    external: true
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.1.0/24
         gateway: 172.16.1.1
