---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: github-mcp
spec:
  mcp:
    targets:
      - name: github-mcp
        static:
          services:
            host: github-mcp.ai.svc.cluster.local
            port: 8082
            policies:
              auth:
                secretRef:
                  name: github-mcp-secret
