---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: github-mcp
spec:
  image: ghcr.io/github/github-mcp-server:v1.0.3
  transport: stdio
  groupRef:
    name: mcp-tools
  secrets:
    - name: github-mcp-secret
      key: GITHUB_PERSONAL_ACCESS_TOKEN
