---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snapotter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: snapotter-secret
    template:
      data:
        # App
        REDIS_URL: |-
          redis://:{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379/16
        # Database
        DATABASE_URL: |-
          postgresql://{{ .SNAPOTTER_POSTGRES_USER }}:{{ .SNAPOTTER_POSTGRES_PASSWORD }}@postgres-pgbouncer-rw.database.svc.cluster.local/{{ .SNAPOTTER_POSTGRES_DB }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .SNAPOTTER_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .SNAPOTTER_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .SNAPOTTER_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: dragonfly
