---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: agentgateway-mcp
spec:
  mcp:
    targets:
      - name: agentgateway-mcp
        selector:
          services:
            matchLabels:
              mcp.home.arpa/server: "true"
      - name: github-mcp
        static:
          host: github-mcp.ai.svc.cluster.local
          port: 8082
          policies:
            auth:
              secretRef:
                name: github-mcp-secret
