---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPRemoteProxy
metadata:
  name: sidero
spec:
  remoteUrl: https://docs.siderolabs.com/mcp
  transport: streamable-http
  groupRef:
    name: mcp-tools
