---
apiVersion: pangolin.home-operations.com/v1alpha1
kind: PublicResource
metadata:
  name: checkmk
  namespace: networking
spec:
  name: checkmk
  siteRef: k8s
  protocol: http
  fullDomain: checkmk.${SECRET_DOMAIN_PANGOLIN}
  ssl: true
  targets:
    - hostname: checkmk.${SECRET_DOMAIN_INT}
      port: 80
      method: http
  auth:
    ssoEnabled: true
    autoLoginIdp: 1
---
apiVersion: pangolin.home-operations.com/v1alpha1
kind: PublicResource
metadata:
  name: nas01
  namespace: networking
spec:
  name: nas01
  siteRef: k8s
  protocol: http
  fullDomain: nas01.${SECRET_DOMAIN_PANGOLIN}
  ssl: true
  targets:
    - hostname: nas01.${SECRET_DOMAIN_INT}
      port: 88
      method: http
  auth:
    ssoEnabled: true
    autoLoginIdp: 1
---
apiVersion: pangolin.home-operations.com/v1alpha1
kind: PublicResource
metadata:
  name: pikvm
  namespace: networking
spec:
  name: pikvm
  siteRef: k8s
  protocol: http
  fullDomain: pikvm.${SECRET_DOMAIN_PANGOLIN}
  ssl: true
  targets:
    - hostname: pikvm.${SECRET_DOMAIN_INT}
      port: 80
      method: http
  auth:
    ssoEnabled: true
    autoLoginIdp: 1
---
apiVersion: pangolin.home-operations.com/v1alpha1
kind: PublicResource
metadata:
  name: prx
  namespace: networking
spec:
  name: prx
  siteRef: k8s
  protocol: http
  fullDomain: prx.${SECRET_DOMAIN_PANGOLIN}
  ssl: true
  targets:
    - hostname: prx.${SECRET_DOMAIN_INT}
      port: 8006
      method: https
  auth:
    ssoEnabled: true
    autoLoginIdp: 1
---
apiVersion: pangolin.home-operations.com/v1alpha1
kind: PublicResource
metadata:
  name: udm
  namespace: networking
spec:
  name: udm
  siteRef: k8s
  protocol: http
  fullDomain: udm.${SECRET_DOMAIN_PANGOLIN}
  ssl: true
  targets:
    - hostname: udm-se.${SECRET_DOMAIN_INT}
      port: 443
      method: https
  auth:
    ssoEnabled: true
    autoLoginIdp: 1
