---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: haos-newt
  namespace: networking
spec:
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: haos-newt-credentials
  data:
    - match:
        secretKey: NEWT_ID
        remoteRef:
          remoteKey: pangolin
          property: HAOS_PANGOLIN_NEWT_ID
    - match:
        secretKey: NEWT_SECRET
        remoteRef:
          remoteKey: pangolin
          property: HAOS_PANGOLIN_NEWT_SECRET
