---
apiVersion: external-secrets.io/v1
kind: PushSecret
metadata:
  name: haos-newt
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  selector:
    secret:
      name: haos-newt-credentials
  data:
    - match:
        secretKey: NEWT_ID
        remoteRef:
          remoteKey: pangolin
          property: HAOS_PANGOLIN_NEWT_ID
    - match:
        secretKey: NEWT_SECRET
        remoteRef:
          remoteKey: pangolin
          property: HAOS_PANGOLIN_NEWT_SECRET
