---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scrob
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: scrob-secret
    template:
      data:
        # App
        SECRET_KEY: "{{ .SCROB_SECRET_KEY }}"
        # Database
        DATABASE_URL: |-
          postgres://{{ .SCROB_POSTGRES_USER }}:{{ .SCROB_POSTGRES_PASSWORD }}@postgres-rw.database.svc.cluster.local/{{ .SCROB_POSTGRES_DB }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .SCROB_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .SCROB_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .SCROB_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: scrob
