---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autopulse
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      autopulse:
        labels:
          nfsMount: "true"
          postgres: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
            envFrom:
              - secretRef:
                  name: autopulse-db-secret
        containers:
          app:
            image:
              repository: ghcr.io/dan-online/autopulse
              tag: v2.0.0@sha256:a9b37936c849b34d3473caf7d83aeddc2c39ec066e18a14a0f4164846d1e4718
            command: ["/bin/autopulse"]
            env:
              TZ: Europe/Berlin
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 2875
    persistence:
      config:
        type: secret
        name: autopulse-secret
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
            readOnly: true
      media:
        type: nfs
        server: nas01.${SECRET_DOMAIN_INT}
        path: /mnt/data/media
        globalMounts:
          - path: /mnt/data/media
            readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          autopulse:
            app:
              - path: /app
                subPath: app
              - path: /tmp
                subPath: tmp
