---
working_dir: ./docker/netbird01
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true
external_secrets:
  TZ: "op://Kubernetes/basic/TZ"
  CLOUDFLARE_EMAIL: "op://Kubernetes/cloudflare/CLOUDFLARE_EMAIL"
  CLOUDFLARE_TRAEFIK_API_TOKEN: "op://Kubernetes/cloudflare/CLOUDFLARE_TRAEFIK_API_TOKEN"
  DOMAIN: "op://Kubernetes/domains/DOMAIN"
  DOMAIN_PANGOLIN: "op://Kubernetes/domains/DOMAIN_PANGOLIN"
  DOMAIN_SHORT: "op://Kubernetes/domains/DOMAIN_SHORT"
