---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: litellm-secret
    template:
      data:
        # App
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        # API
        OPENCODE_GO_API_KEY: "{{ .OPENCODE_API_KEY }}"
        LLAMA_API_KEY: '{{ .LLAMA_API_KEY }}'
  dataFrom:
    - extract:
        key: llama
    - extract:
        key: litellm
    - extract:
        key: opencode
