---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: moltis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: moltis-secret
    template:
      data:
        ## Github
        GH_TOKEN: "{{ .OPENCLAW_GH_TOKEN }}"
        ## API Keys
        MINIMAX_API_KEY: &apikey "{{ .MINIMAX_API_KEY }}"
        ## Apps
        GOOGLE_TOKEN: "{{ .OPENCLAW_GOOGLE_TOKEN }}"
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        PLEX_URL: "{{ .PLEX_URL }}"
        ## HASS
        HA_URL: "https://home.${SECRET_DOMAIN}"
        HA_TOKEN: "{{ .OPENCLAW_HASS_TOKEN }}"
        ## Connections
        OPENCLAW_PHONE_NUMBER: "{{ .OPENCLAW_PHONE_NUMBER }}"
        WHATSAPP_PHONE_NUMBER: "{{ .WHATSAPP_PHONE_NUMBER }}"
        ## Moltis
        MOLTIS_API_KEY: *apikey
        MOLTIS_PASSWORD: "{{ .MOLTIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: github
    - extract:
        key: google
    - extract:
        key: home-assistant
    - extract:
        key: minimax
    - extract:
        key: moltis
    - extract:
        key: openai
    - extract:
        key: openclaw
    - extract:
        key: plex
