---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grimmory-secret
    template:
      data:
        MARIADB_PASSWORD: &dbpass "{{ .GRIMMORY_MARIADB_PASSWORD }}"
        DATABASE_PASSWORD: *dbpass
        MARIADB_ROOT_PASSWORD: "{{ .GRIMMORY_MARIADB_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: grimmory
