---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: colota-forwarder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: colota-forwarder-secret
    template:
      data:
        # App
        API_KEY: "{{ .COLOTA_FORWARDER_API_KEY }}"
        # Connections
        TARGET_1_URL: "{{ .TARGET_1_URL }}"
        TARGET_1_TYPE: owntracks
        TARGET_1_FILTER_TID: sj
        TARGET_2_URL: "{{ .TARGET_2_URL }}"
        TARGET_2_TYPE: owntracks
        TARGET_2_FILTER_TID: lj
        TARGET_3_URL: "{{ .TARGET_3_URL }}"
        TARGET_3_TYPE: colota
        TARGET_3_BATCH_MODE: latest
  dataFrom:
    - extract:
        key: colota-forwarder
