---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filebrowser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: filebrowser-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: filebrowser-configmap
            items:
              - key: config.yaml
  dataFrom:
    - extract:
        key: pocket-id
