---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - ./bentopdf/ks.yaml
  - ./convertx/ks.yaml
  - ./it-tools/ks.yaml
  - ./pairdrop/ks.yaml
  - ./snapotter/ks.yaml
components:
  - ../../components/alerts
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
