---
working_dir: ./docker/nas01
auto_discovery:
  enabled: true
  depth: 1
  delete: true
external_secrets:
  CLOUDFLARE_EMAIL: "op://Kubernetes/cloudflare/CLOUDFLARE_EMAIL"
  CLOUDFLARE_TRAEFIK_API_TOKEN: "op://Kubernetes/cloudflare/CLOUDFLARE_TRAEFIK_API_TOKEN"
  DOMAIN: "op://Kubernetes/domains/DOMAIN"
  DOMAIN_INT: "op://Kubernetes/domains/DOMAIN_INT"
  GARAGE_RPC_SECRET: "op://Kubernetes/garage/GARAGE_RPC_SECRET"
  GARAGE_ADMIN_TOKEN: "op://Kubernetes/garage/GARAGE_ADMIN_TOKEN"
  LLAMA_API_KEY: "op://Kubernetes/llama/LLAMA_API_KEY"
  TZ: "op://Kubernetes/basic/TZ"
  UNIFI_API_KEY: op://Kubernetes/unifi/UNIFI_API_KEY
  ZEROBYTE_APP_SECRET: "op://Kubernetes/zerobyte/ZEROBYTE_APP_SECRET"
  ZOT_HTPASSWD: op://Kubernetes/zot/ZOT_HTPASSWD
  ZOT_OIDC_CLIENT_ID: op://Kubernetes/pocket-id/ZOT_CLIENT_ID
  ZOT_OIDC_CLIENT_SECRET: op://Kubernetes/pocket-id/ZOT_CLIENT_SECRET
  ZOT_SESSION_KEYS: op://Kubernetes/zot/ZOT_SESSION_KEYS
force_recreate: false
reconciliation:
  enabled: true
  interval: 3600
