---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mail-archiver
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      mail-archiver:
        labels:
          postgres: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
            envFrom: &envFrom
              - secretRef:
                  name: mail-archiver-secret
        containers:
          app:
            image:
              repository: ghcr.io/s1t5/mailarchiver
              tag: 2606.4@sha256:be7a56d1a97dd223408300ee9009bcb5b06be9c67bfd818181a0036f3cfdec12
            env:
              TZ: Europe/Berlin
              Authentication__Enabled: true
              MailSync__IntervalMinutes: 120
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 4000Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 5000
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN_INTERNAL}"
        parentRefs:
          - name: envoy-internal
            namespace: networking
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/DataProtection-Keys
