---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: drag0n141-bot-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: drag0n141-bot-pem-secret
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: github
        property: GITHUB_DRAG0N141_BOT_PRIVATE_KEY
