---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: drag0n141-bot-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: drag0n141-bot-pem-secret
    template:
      data:
        private_key_pem: |-
          {{ .GITHUB_DRAG0N141_BOT_PRIVATE_KEY }}
  dataFrom:
    - extract:
        key: github
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovator-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovator-operator-secret
    template:
      data:
        RENOVATE_REDIS_URL: |-
          redis://:{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379/7
        # Dockerhub
        DOCKERHUB_TOKEN: "{{ .DOCKERHUB_TOKEN }}"
        DOCKERHUB_USERNAME: "{{ .DOCKERHUB_USERNAME }}"
  dataFrom:
    - extract:
        key: dockerhub
    - extract:
        key: dragonfly
