---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wallos
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      wallos:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/ellite/wallos
              tag: 5.4.2@sha256:316f26e13265958e7946ef98ff600516fddc51d698ee98bd1ae1577e5e00789f
            env:
              TZ: Europe/Berlin
              OIDC_ENABLED: true
              OIDC_PROVIDER_NAME: Pocket ID
              OIDC_SCOPES: "openid profile email"
              OIDC_AUTH_URL: "https://id.${SECRET_DOMAIN}/authorize"
              OIDC_TOKEN_URL: "https://id.${SECRET_DOMAIN}/api/oidc/token"
              OIDC_ISSUER_URL: "https://id.${SECRET_DOMAIN}"
              OIDC_USERINFO_URL: "https://id.${SECRET_DOMAIN}/api/oidc/userinfo"
              OIDC_REDIRECT_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN_INTERNAL}"
              OIDC_LOGOUT_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN_INTERNAL}"
              OIDC_USER_IDENTIFIER: email
              OIDC_AUTO_CREATE_USER: true
              SSRF_ALLOWLIST: id.${SECRET_DOMAIN},smtp-relay.networking.svc.cluster.local
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-oidc-credentials"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN_INTERNAL}"
        parentRefs:
          - name: envoy-internal
            namespace: networking
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          wallos:
            app:
              - path: /var/www/html/db
                subPath: db
              - path: /var/www/html/images/uploads/logos
                subPath: logos
