host: https://mcp.${SECRET_DOMAIN}/
authorization:
  server: https://mcp-dex.${SECRET_DOMAIN}/
  serverMetadataProxyEnabled: true
  authorizationProxyEnabled: true
  dynamicClientRegistration:
    enabled: true
dexGRPCClient:
  addr: dex.ai.svc.cluster.local:5557
proxy:
  - path: /mcp
    http:
      url: http://agentgateway-mcp.ai.svc.cluster.local:3000
    authentication:
      enabled: true
