---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: toolhive-secret
    template:
      data:
        # App
        TOOLHIVE_SIGNING_KEY: "{{ .TOOLHIVE_SIGNING_KEY }}"
        TOOLHIVE_HMAC_KEY: "{{ .TOOLHIVE_HMAC_KEY }}"
        # OIDC
        TOOLHIVE_CLIENT_SECRET: "{{ .TOOLHIVE_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: pocket-id
    - extract:
        key: toolhive
