---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPOIDCConfig
metadata:
  name: mcp-gateway-oidc
spec:
  type: inline
  inline:
    issuer: https://mcp.${SECRET_DOMAIN}
    jwksAllowPrivateIP: true
