---
apiVersion: toolhive.stacklok.com/v1beta1
kind: MCPOIDCConfig
metadata:
  name: mcp-gateway-oidc
spec:
  type: oidc
  oidcConfig:
    type: inline
    resourceUrl: https://mcp.${SECRET_DOMAIN}/mcp
    inline:
      issuer: https://mcp.${SECRET_DOMAIN}
      jwksAllowPrivateIP: true
