---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: toolhive
spec:
  name: Toolhive
  callbackUrls:
    - "https://mcp.${SECRET_DOMAIN}/oauth/callback"
  allowedUserGroups:
    - name: id-admin
      namespace: security
  logo:
    autoGenerate: false
