---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: moltis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: moltis-secret
    template:
      data:
        ## API Keys
        MINIMAX_API_KEY: &apikey "{{ .MINIMAX_API_KEY }}"
        ## Apps
        GOOGLE_CALENDAR_TOKEN: |-
          "{{ .GOOGLE_CALENDAR_TOKEN }}"
        ## Connections
        OPENCLAW_PHONE_NUMBER: "{{ .OPENCLAW_PHONE_NUMBER }}"
        WHATSAPP_PHONE_NUMBER: "{{ .WHATSAPP_PHONE_NUMBER }}"
        ## Moltis
        MOLTIS_API_KEY: *apikey
        MOLTIS_PASSWORD: "{{ .MOLTIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: google
    - extract:
        key: minimax
    - extract:
        key: moltis
    - extract:
        key: openclaw
