---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-mcp-secret
    template:
      data:
        AUTH_TOKEN: &token "{{ .N8N_MCP_AUTH_TOKEN }}"
        N8N_API_KEY: "{{ .N8N_MCP_API_KEY }}"
        MCP_AUTH_TOKEN: *token
        Authorization: "Bearer {{ .N8N_MCP_AUTH_TOKEN }}"
  dataFrom:
    - extract:
        key: n8n
