---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: n8n-mcp
spec:
  image: ghcr.io/czlonkowski/n8n-mcp:2.50.3
  transport: stdio
  groupRef:
    name: mcp-tools
  env:
    - name: MCP_MODE
      value: stdio
    - name: N8N_API_URL
      value: https://n8n.${SECRET_DOMAIN_INTERNAL}
  secrets:
    - name: n8n-mcp-secret
      key: N8N_API_KEY
