---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: prometheus-mcp
spec:
  image: ghcr.io/pab1it0/prometheus-mcp-server:1.6.1
  transport: stdio
  groupRef:
    name: mcp-tools
  env:
    - name: PROMETHEUS_URL
      value: http://prometheus-operated.monitoring.svc.cluster.local:9090
    - name: PROMETHEUS_DISABLE_LINKS
      value: "true"
