---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: forgejo
spec:
  name: Forgejo
  callbackUrls:
    - "https://forgejo.${SECRET_DOMAIN_INTERNAL}/user/oauth2/PocketID/callback"
  allowedUserGroups:
    - name: id-admin
      namespace: security
