---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dawarich-secret
    template:
      data:
        # App
        SECRET_KEY_BASE: "{{ .DAWARICH_SECRET_KEY_BASE }}"
        REDIS_URL: |-
          redis://:{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379/2
        # Database
        DATABASE_HOST: &dbhost "postgres-rw.database.svc.cluster.local"
        DATABASE_PORT: "5432"
        DATABASE_USERNAME: &dbuser "{{ .DAWARICH_POSTGRES_USER }}"
        DATABASE_PASSWORD: &dbpass "{{ .DAWARICH_POSTGRES_PASSWORD }}"
        DATABASE_NAME: &dbname "{{ .DAWARICH_POSTGRES_DB }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: dawarich
    - extract:
        key: dragonfly
