apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./hermes/ks.yaml
  - ./litellm/ks.yaml
  - ./mcp
  - ./ollama/ks.yaml
  - ./open-webui/ks.yaml
  - ./toolhive/ks.yaml
components:
  - ../../components/alerts
  - ../../components/namespace
  - ../../components/repos
  - ../../components/substitutions
