---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ha-mcp
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      ha-mcp:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/homeassistant-ai/ha-mcp
              tag: 7.0.0@sha256:e0be3a374d3fac95759b4e0e698148dd19066a3242b814d12deb26c0ef840d99
            command:
              - ha-mcp-web
            env:
              TZ: ${TIMEZONE}
              HOMEASSISTANT_URL: http://haos.${SECRET_DOMAIN_INT}:8123
            envFrom:
              - secretRef:
                  name: ha-mcp-secret
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        labels:
          mcp.home.arpa/server: "true"
        ports:
          http:
            appProtocol: kgateway.dev/mcp
            port: 8086
    route:
      app:
        parentRefs:
          - name: agentgateway-mcp
            namespace: ai
        rules:
          - backendRefs:
              - name: agentgateway-mcp
                group: agentgateway.dev
                kind: AgentgatewayBackend
