---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-migadu-token"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: "${APP}-migadu-token"
    template:
      data:
        MIGADU_USERNAME: "{{ .MIGADU_USERNAME }}"
        MIGADU_TOKEN: "{{ .TERRAFORM_MIGADU_TOKEN }}"
        TF_VAR_destination_local_part: "{{ .MIGADU_LOCAL_PART }}"
  dataFrom:
    - extract:
        key: migadu
