---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: gotify
spec:
  interval: 12h
  approvePlan: auto
  backendConfig:
    customConfiguration: |
      backend "s3" {
        bucket   = "terraform"
        key      = "gotify/gotify.tfstate"
        region   = "auto"
        endpoints = {
          s3 = "https://${SECRET_CLOUDFLARE_R2_ID}.r2.cloudflarestorage.com"
        }

        skip_credentials_validation = true
        skip_requesting_account_id  = true
        skip_metadata_api_check     = true
        skip_region_validation      = true
        use_path_style              = true
      }
  backendConfigsFrom:
    - kind: Secret
      name: terraform-backend-secret
  path: ./gotify
  sourceRef:
    kind: OCIRepository
    name: terraform
  varsFrom:
    - kind: Secret
      name: terraform-secret
