---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pocket-id-operator
  namespace: &namespace security
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/security/pocket-id-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 1h
  retryInterval: 2m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pocket-id-instance
  namespace: &namespace security
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
    - name: onepassword-connect
      namespace: external-secrets
    - name: pocket-id-operator
      namespace: *namespace
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  components:
    - ../../../../components/volsync
  path: ./kubernetes/apps/security/pocket-id-operator/instance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      APP: pocket-id
      VOLSYNC_CAPACITY: 1Gi
