{
 "title": "APC UPS",
 "description": "Displays monitoring data collected from APC uninterruptible power supplies via SNMP.",
 "tags": [
  "APC",
  "apcupsd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsBasicOutputStatus" }
   ]
  },
  {
   "title": "Mains frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "upsAdvInputFrequency" }
   ]
  },
  {
   "title": "Time spent on battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "upsBasicBatteryTimeOnBattery" }
   ]
  },
  {
   "title": "UPS load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "upsAdvOutputActivePower" }
   ]
  },
  {
   "title": "Self-test result",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsAdvTestDiagnosticsResults" }
   ]
  },
  {
   "title": "Self-test schedule",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsAdvTestDiagnosticSchedule" }
   ]
  },
  {
   "title": "Battery charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "upsAdvBatteryCapacity" }
   ]
  },
  {
   "title": "Battery temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsAdvBatteryTemperature" }
   ]
  },
  {
   "title": "Estimated uptime on batteries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "upsAdvBatteryRunTimeRemaining / 100"
    }
   ]
  },
  {
   "title": "Reason for last transfer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "upsAdvInputLineFailCause" }
   ]
  },
  {
   "title": "Battery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      { "expr": "upsAdvBatteryActualVoltage", "legendFormat": "actual" },
      { "expr": "upsAdvBatteryNominalVoltage", "legendFormat": "nominal" }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      { "expr": "upsAdvBatteryTemperature" }
     ]
    },
    {
     "title": "Charge",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "upsAdvBatteryCapacity" }
     ]
    }
   ]
  },
  { "title": "AC and load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "upsAdvInputLineVoltage", "legendFormat": "input" },
    { "expr": "upsAdvOutputVoltage", "legendFormat": "output" }
   ]
  },
  {
   "title": "Output load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "upsAdvOutputActivePower" }
   ]
  }
 ]
}