---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pangolin-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pangolin-operator-secret
    creationPolicy: Owner
    template:
      data:
        PANGOLIN_API_URL: "{{ .PANGOLIN_API_URL }}"
        PANGOLIN_API_KEY: "{{ .PANGOLIN_API_KEY }}"
        PANGOLIN_ENDPOINT: "{{ .PANGOLIN_ENDPOINT }}"
        PANGOLIN_ORG_ID: "{{ .PANGOLIN_ORG_ID }}"
  dataFrom:
    - extract:
        key: pangolin
