---
working_dir: ./docker/pangolin01
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true
external_secrets:
  TZ: "op://Kubernetes/basic/TZ"
  CLOUDFLARE_EMAIL: "op://Kubernetes/cloudflare/CLOUDFLARE_EMAIL"
  CLOUDFLARE_TRAEFIK_API_TOKEN: "op://Kubernetes/cloudflare/CLOUDFLARE_TRAEFIK_API_TOKEN"
  DOMAIN: "op://Kubernetes/domains/DOMAIN"
  DOMAIN_PANGOLIN: "op://Kubernetes/domains/DOMAIN_PANGOLIN"
  DOMAIN_SHORT: "op://Kubernetes/domains/DOMAIN_SHORT"
  MAXMIND_ACCOUNT_ID: op://Kubernetes/maxmind/MAXMIND_ACCOUNT_ID
  MAXMIND_PANGOLIN_LICENSE_KEY: op://Kubernetes/maxmind/MAXMIND_LICENSE_KEY
  PANGOLIN_SERVER_SECRET: op://Kubernetes/pangolin/PANGOLIN_SERVER_SECRET
  CROWDSEC_TRAEFIK_API_KEY: op://Kubernetes/pangolin/CROWDSEC_TRAEFIK_API_KEY
