---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linux-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: linux-mcp-secret
    template:
      data:
        id_ed25519: |-
          {{ .SSH_PRIVATE_KEY }}
  dataFrom:
    - extract:
        key: linux
