---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linux-mcp
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      linux-mcp:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/drag0n141/linux-mcp
              tag: v1.0.0@sha256:648ab2b46ed3d15f8003178a8cf8af6250d0bb843d79043bcae311688edab729
            env:
              TZ: ${TIMEZONE}
              LINUX_MCP_TRANSPORT: streamable-http
              LINUX_MCP_HOST: 0.0.0.0
              LINUX_MCP_SSH_USER: root
              LINUX_MCP_EXECUTE_ENABLED: true
              LINUX_MCP_ALLOWED_COMMANDS: "curl,python3,pip"
            envFrom:
              - secretRef:
                  name: linux-mcp-secret
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 0
    service:
      app:
        labels:
          mcp.home.arpa/server: "true"
        ports:
          http:
            appProtocol: kgateway.dev/mcp
            port: 8000
    route:
      app:
        parentRefs:
          - name: agentgateway-mcp
            namespace: ai
        rules:
          - backendRefs:
              - name: agentgateway-mcp
                group: agentgateway.dev
                kind: AgentgatewayBackend
    persistence:
      config:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        globalMounts:
          - path: /var/lib/mcp/.ssh/config
            subPath: config
            readOnly: true
      ssh:
        type: secret
        name: "{{ .Release.Name }}-secret"
        defaultMode: 0400
        globalMounts:
          - path: /var/lib/mcp/.ssh/id_ed25519
            subPath: id_ed25519
            readOnly: true
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /var/lib/mcp/.local/share/linux-mcp-server/logs
