---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes-secret
    template:
      data:
        ## API Keys
        MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
        ## Apps
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        PLEX_URL: "{{ .PLEX_URL }}"
        ## Connections
        WHATSAPP_ALLOWED_USERS: "{{ .WHATSAPP_PHONE_NUMBER }}"
        TELEGRAM_ALLOWED_USERS: "{{ .TELEGRAM_USER_ID }}"
        TELEGRAM_BOT_TOKEN: "{{ .HERMES_BOT_TOKEN }}"
        ## Hermes
        API_SERVER_KEY: "{{ .HERMES_API_SERVER_KEY }}"
  dataFrom:
    - extract:
        key: hermes
    - extract:
        key: plex
    - extract:
        key: minimax
    - extract:
        key: telegram
    - extract:
        key: whatsapp
