---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes-secret
    template:
      data:
        ## API Keys
        MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
        ## Apps
        GOOGLE_CALENDAR_TOKEN: |-
          "{{ .GOOGLE_CALENDAR_TOKEN }}"
        ## Connections
        OPENCLAW_PHONE_NUMBER: "{{ .OPENCLAW_PHONE_NUMBER }}"
        WHATSAPP_PHONE_NUMBER: "{{ .WHATSAPP_PHONE_NUMBER }}"
  dataFrom:
    - extract:
        key: google
    - extract:
        key: minimax
    - extract:
        key: openclaw
