---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: geopulse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: geopulse-secret
    template:
      data:
        # App
        GEOPULSE_POSTGRES_PASSWORD: &dbpass "{{ .GEOPULSE_POSTGRES_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .GEOPULSE_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .GEOPULSE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # OIDC
        GEOPULSE_OIDC_PROVIDER_GENERIC_CLIENT_ID: "{{ .GEOPULSE_CLIENT_ID }}"
        GEOPULSE_OIDC_PROVIDER_GENERIC_CLIENT_SECRET: "{{ .GEOPULSE_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: pocket-id
