---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: geopulse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: geopulse-secret
    template:
      data:
        # App
        ai-encryption-key.txt: "{{ .AI_ENCRYPTION_KEY }}"
        jwt-private-key.pem: |-
          "{{ .JWT_PRIVATE_KEY }}"
        jwt-public-key.pem: |-
          "{{ .JWT_PUBLIC_KEY }}"
        GEOPULSE_POSTGRES_USERNAME: &dbuser "{{ .GEOPULSE_POSTGRES_USER }}"
        GEOPULSE_POSTGRES_PASSWORD: &dbpass "{{ .GEOPULSE_POSTGRES_PASSWORD }}"
        GEOPULSE_POSTGRES_URL: |-
          jdbc:postgresql://postgres-rw.database.svc.cluster.local:5432/{{ .GEOPULSE_POSTGRES_DB }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .GEOPULSE_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: geopulse
