---
apiVersion: v1
kind: ConfigMap
metadata:
  name: geopulse-initdb
data:
  geopulse_db.sql: |
    CREATE SCHEMA IF NOT EXISTS extensions;
    CREATE EXTENSION IF NOT EXISTS postgis SCHEMA extensions;
    CREATE EXTENSION IF NOT EXISTS postgis_topology SCHEMA topology;
    ALTER ROLE geopulse SET search_path TO public, extensions, topology;
