---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: geopulse
spec:
  name: Geopulse
  callbackUrls:
    - "https://geopulse.${SECRET_DOMAIN_INTERNAL}/oidc/callback"
  allowedUserGroups:
    - name: id-admin
      namespace: security
    - name: id-home
      namespace: security
  secret:
    keys:
      clientID: GEOPULSE_OIDC_PROVIDER_GENERIC_CLIENT_ID
      clientSecret: GEOPULSE_OIDC_PROVIDER_GENERIC_CLIENT_SECRET

