---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: geopulse-oidc
spec:
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: geopulse-oidc-credentials
  data:
    - match:
        secretKey: client_id
        remoteRef:
          remoteKey: pocket-id
          property: GEOPULSE_CLIENT_ID
    - match:
        secretKey: client_secret
        remoteRef:
          remoteKey: pocket-id
          property: GEOPULSE_CLIENT_SECRET
