---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bentopdf
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      bentopdf:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/alam00000/bentopdf
              tag: 2.8.0@sha256:ba7f40784abbe9f2ce36c1f982d47608cedb4104cc792c13b2965161f02ee16b
            env:
              TZ: ${TIMEZONE}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 1000Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
    service:
      app:
        annotations:
          pangolin-operator/site-ref: k8s
          pangolin-operator/auth-sso: "true"
          pangolin-operator/auth-sso-idp: "1"
          pangolin-operator/full-domain: "pdf.${SECRET_DOMAIN_PANGOLIN}"
        ports:
          http:
            port: &port 8080
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames:
          - "pdf.${SECRET_DOMAIN_INTERNAL}"
        parentRefs:
          - name: envoy-internal
            namespace: networking
    persistence:
      tmpfs:
        type: emptyDir
        advancedMounts:
          bentopdf:
            app:
              - path: /tmp
                subPath: tmp
