allow_anonymous false
autosave_interval 60
connection_messages false
password_file /mosquitto/external_config/mosquitto_pwd
per_listener_settings false
persistence true
persistence_location /data
listener 1883
protocol mqtt

listener 8083
protocol websockets