---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: termix
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s
  target:
    name: termix-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: termix-configmap
            items:
              - key: config.yml
  dataFrom:
    - extract:
        key: openpubkey-ssh-oidc-credentials
