---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: termix
spec:
  target:
    name: termix-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: termix-configmap
            items:
              - key: config.yml
  dataFrom:
      - sourceRef:
          storeRef:
            kind: ClusterSecretStore
            name: k8s
        extract:
          key: openpubkey-ssh-oidc-credentials
          namespace: security
