---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: termix
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      termix:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/lukegus/termix
              tag: release-2.1.0@sha256:52e45c1ea3fb85be5b3ade5ff42eed0946fe81131cbd834f6960e00797f17f86
            env:
              TZ: ${TIMEZONE}
              PORT: &port 8080
              ENABLE_GUACAMOLE: true
              GUACD_HOST: termix-guacd.default.svc.cluster.local
              GUACD_PORT: "4822"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        annotations:
          pangolin-operator/site-ref: k8s
          pangolin-operator/auth-sso: "true"
          pangolin-operator/auth-sso-idp: "1"
          pangolin-operator/full-domain: "{{ .Release.Name }}.${SECRET_DOMAIN_PANGOLIN}"
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN_INTERNAL}"
        parentRefs:
          - name: envoy-internal
            namespace: networking
    persistence:
      config:
        type: secret
        name: "{{ .Release.Name }}-secret"
        globalMounts:
          - path: /app/data/.opk/config.yml
            subPath: config.yml
            readOnly: true
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/data
