---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calendar-mcp
  namespace: &namespace ai
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
    - name: toolhive-operator-crds
      namespace: *namespace
  path: ./kubernetes/apps/ai/calendar-mcp/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 1h
  retryInterval: 2m
  timeout: 5m
