---
services:
  wireguard:
    image: 'ghcr.io/linuxserver/wireguard:1.0.20260223'
    hostname: 'wireguard'
    container_name: 'wireguard'
    restart: 'always'
    cap_drop:
      - 'ALL'
    cap_add:
      - 'NET_ADMIN'
    tmpfs:
      - '/run:exec'
      - '/tmp'
    volumes:
      - '/opt/appdata/wireguard:/config:rw'
    configs:
      - source: 'wg0_conf'
        target: '/config/wg_confs/wg0.conf'
        mode: 0600
    environment:
      - 'TZ=${TZ}'
      - 'PUID=1000'
      - 'PGID=1000'
    ports:
      - '51820:51820/udp'
    network_mode: 'host'
    security_opt:
      - 'no-new-privileges:true'
    deploy:
      resources:
        limits:
          memory: 128M

configs:
  wg0_conf:
    content: |-
      [Interface]
      PrivateKey = ${WG_PANGOLIN01_PRIVATE_KEY}
      Address = 192.168.251.2/24

      [Peer]
      PublicKey = ${WG_UNIFI_EXT_PUBLIC_KEY}
      PresharedKey = ${WG_PRESHARED_KEY}
      Endpoint = ipv4.${DOMAIN}:51240
      AllowedIPs = 192.168.0.0/16
      PersistentKeepalive = 25
