---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: checkmk
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: checkmk-secret
    template:
      data:
        # App
        CMK_PASSWORD: "{{ .CHECKMK_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: checkmk
