---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket-id
spec:
  template:
    spec:
      initContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:18@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
          envFrom:
            - secretRef:
                name: pocket-id-secret
