---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDInstance
metadata:
  name: &app pocket-id
spec:
  image: ghcr.io/pocket-id/pocket-id:v2.6.2-distroless@sha256:a9adc636b5d30098307b8a1292c5887a59690cd5429aac5e87b588852f9c346d
  timezone: "${TIMEZONE}"
  appUrl: "https://id.${SECRET_DOMAIN}"
  databaseUrl:
    valueFrom:
      secretKeyRef:
        name: &secret pocket-id-secret
        key: DB_CONNECTION_STRING
  encryptionKey:
    valueFrom:
      secretKeyRef:
        name: *secret
        key: ENCRYPTION_KEY
  env:
    - name: LDAP_BIND_DN
      valueFrom:
        secretKeyRef:
          name: *secret
          key: LDAP_BIND_DN
    - name: LDAP_BASE
      valueFrom:
        secretKeyRef:
          name: *secret
          key: LDAP_BASE
    - name: LDAP_USER_SEARCH_FILTER
      valueFrom:
        secretKeyRef:
          name: *secret
          key: LDAP_USER_SEARCH_FILTER
  ldap:
    url: "ldaps://ldap-lb.security.svc.cluster.local"
    bindPassword:
      valueFrom:
        secretKeyRef:
          name: *secret
          key: LDAP_BIND_PASSWORD
    skipCertVerify: true
    adminGroupName: "ID-Admin"
    userGroupSearchFilter: "(&(objectClass=group)(cn=ID*))"
    attributeMapping:
      userUniqueIdentifier: "objectGUID"
      groupUniqueIdentifier: "objectGUID"
      userFirstName: "givenName"
      userLastName: "sn"
      userUsername: "sAMAccountName"
      userEmail: "mail"
      groupMember: "member"
      groupName: "cn"
  smtp:
    host: "smtp-relay.networking.svc.cluster.local"
    port: 2525
    from: "pocket-id@${SECRET_DOMAIN}"
  geoip:
    dbPath: "/app/data/GeoLite2-City.mmdb"
    maxmindLicenseKey:
      valueFrom:
        secretKeyRef:
          name: *secret
          key: MAXMIND_LICENSE_KEY
  ui:
    sessionDuration: 43800
  userManagement:
    emailsVerified: true
  logging:
    level: "info"
  metrics:
    enabled: true
  analyticsDisabled: true
  versionCheckDisabled: true
  route:
    enabled: true
    parentRefs:
      - name: envoy-external
        namespace: networking
    hostnames:
      - "id.${SECRET_DOMAIN}"
  persistence:
    enabled: true
    existingClaim: *app
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 256Mi
