---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-icons
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pocket-id-icons-secret
    template:
      data:
        POCKET_ID_API_KEY : "{{ .POCKETID_API_KEY }}"
  dataFrom:
    - extract:
        key: pocket-id
