---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: timescaledb
spec:
  images:
    - major: 18
      # renovate: datasource=docker depName=timescale/timescaledb-ha
      image: timescale/timescaledb-ha:pg18.3-ts2.25.2@sha256:a222a11e75099f521dceaee56b2fae15d0277f02e0360f29350925c08448e415
