---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: timescaledb
spec:
  images:
    - major: 18
      # renovate: datasource=docker depName=timescale/timescaledb-ha
      image: timescale/timescaledb-ha:pg18.3-ts2.25.2@sha256:a743be037e944f23418fdddcf231f10aa0bc3ae2ee1218a0f8005915313f7a78
