---
apiVersion: v1
kind: Service
metadata:
  name: postgres-timescale-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres-timescale.${SECRET_DOMAIN_INTERNAL}
    io.cilium/lb-ipam-ips: 192.168.222.108
    gatus.home-operations.com/endpoint: |-
      group: infrastructure
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres-timescale
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-timescale
    cnpg.io/instanceRole: primary
