---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraform-backend
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: terraform-backend-secret
    template:
      data:
        access_key: "{{ .CLOUDFLARE_AWS_ACCESS_KEY_ID }}"
        secret_key: "{{ .CLOUDFLARE_AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: cloudflare
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraform
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: terraform-secret
    template:
      data:
        OP_CONNECT_TOKEN: "{{ .OP_CONNECT_TOKEN }}"
        OP_CONNECT_HOST: "http://onepassword-connect.external-secrets.svc.cluster.local"
  dataFrom:
    - extract:
        key: 1password
