---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tofu-controller
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
    runner:
      image:
        repository: ghcr.io/home-operations/opentofu-runner
        tag: 1.11.6@sha256:10e1c1dc9160e9dbb1d9832d708fd42d8bf0826e090cee084c804413f971e800
