---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tofu-controller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tofu-controller
  values:
    fullnameOverride: *app
    replicaCount: 1
    runner:
      image:
        repository: ghcr.io/home-operations/opentofu-runner
        tag: 1.11.6@sha256:10e1c1dc9160e9dbb1d9832d708fd42d8bf0826e090cee084c804413f971e800
      grpc:
        maxMessageSize: 30
      serviceAccount:
        allowedNamespaces:
          - "*"
    logLevel: info
    allowBreakTheGlass: false
    allowCrossNamespaceRefs: true
    usePodSubdomainResolution: true
    clusterDomain: cluster.local
    concurrency: 24
    caCertValidityDuration: 24h
    certRotationCheckFrequency: 30m
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 512Mi
