---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: tandoor-oidc
spec:
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: tandoor-oidc-credentials
  data:
    - match:
        secretKey: client_id
        remoteRef:
          remoteKey: pocket-id
          property: TANDOOR_CLIENT_ID
    - match:
        secretKey: client_secret
        remoteRef:
          remoteKey: pocket-id
          property: TANDOOR_CLIENT_SECRET
