---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: openpubkey-ssh-oidc
spec:
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: openpubkey-ssh-oidc-credentials
  data:
    - match:
        secretKey: client_id
        remoteRef:
          remoteKey: pocket-id
          property: OPKSSH_CLIENT_ID
