---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zerobyte-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zerobyte-exporter-secret
    template:
      data:
        ZEROBYTE_USERNAME: "{{ .ZEROBYTE_USERNAME }}"
        ZEROBYTE_PASSWORD: "{{ .ZEROBYTE_PASSWORD }}"
  dataFrom:
    - extract:
        key: zerobyte
