---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whisper
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: whisper-secret
    creationPolicy: Owner
    template:
      data:
        HASS_LONG_LIVED_TOKEN: "{{ .WHISPER_HASS_TOKEN }}"
  dataFrom:
    - extract:
        key: home-assistant
