---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: prometheus-mcp
spec:
  image: ghcr.io/pab1it0/prometheus-mcp-server:1.6.0
  transport: stdio
  groupRef: mcp-tools
  env:
    - name: PROMETHEUS_URL
      value: http://prometheus-operated.monitoring.svc.cluster.local:9090
    - name: PROMETHEUS_DISABLE_LINKS
      value: true
