---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-router
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: mc-router
  values:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi
    services:
      minecraft:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "mc-router.${SECRET_DOMAIN_INTERNAL}"
          lbipam.cilium.io/ips: 192.168.222.160
