---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ha-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ha-mcp-secret
    template:
      data:
        HOMEASSISTANT_TOKEN: "{{ .MCP_HASS_TOKEN }}"
  dataFrom:
    - extract:
        key: home-assistant
