---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: ha-mcp
spec:
  image: ghcr.io/homeassistant-ai/ha-mcp:7.7.0
  transport: streamable-http
  groupRef:
    name: mcp-tools
  env:
    - name: HOMEASSISTANT_URL
      value: http://haos.${SECRET_DOMAIN_INT}:8123
    - name: TMPDIR
      value: /tmp
  secrets:
    - name: ha-mcp-secret
      key: HOMEASSISTANT_TOKEN
  podTemplateSpec:
    spec:
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: mcp
          command:
            - ha-mcp-web
          volumeMounts:
            - name: tmp
              mountPath: /tmp
