---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: change-detection
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      change-detection:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: 0.55.8@sha256:5438423d5e906eff4e8f7886823482ad23f472bf7b8530ccaca89fb48c337882
            env:
              TZ: Europe/Berlin
              BASE_URL: https://change-detection.${SECRET_DOMAIN_INTERNAL}
              PLAYWRIGHT_DRIVER_URL: "ws://localhost:3000/chrome?stealth=1&--disable-web-security=true"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 250Mi
          browserless:
            image:
              repository: ghcr.io/browserless/chrome
              tag: v2.55.4@sha256:e4ff3bb8537fe4c2f2c102b7984f3b71250bb323f8ce7ff5b1127c76bec1bf40
            env:
              TZ: Europe/Berlin
              TIMEOUT: 60000
            securityContext:
              runAsUser: 999
              runAsGroup: 999
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 2000Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        annotations:
          pangolin-operator/enabled: "true"
          pangolin-operator/site-ref: k8s
          pangolin-operator/auth-sso: "true"
          pangolin-operator/auth-sso-idp: "1"
          pangolin-operator/full-domain: "{{ .Release.Name }}.${SECRET_DOMAIN_PANGOLIN}"
        ports:
          http:
            port: 5000
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN_INTERNAL}"
        parentRefs:
          - name: envoy-internal
            namespace: networking
    persistence:
      data:
        existingClaim: change-detection
        advancedMounts:
          change-detection:
            app:
              - path: /datastore
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
