---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: change-detection
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      change-detection:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: 0.55.1@sha256:1cb94f27cac395c90ea4c7a1ea891b241c9a5d5231483961a782312545aadeec
            env:
              TZ: ${TIMEZONE}
              BASE_URL: https://change-detection.${SECRET_DOMAIN_INTERNAL}
              PLAYWRIGHT_DRIVER_URL: "ws://localhost:3000/chrome?stealth=1&--disable-web-security=true"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 250Mi
          browserless:
            image:
              repository: ghcr.io/browserless/chrome
              tag: v2.48.0@sha256:d7c2931b77472603d7e16a0626edbb78eee2c9c6e006cd2ada8fe5df2290b11b
            env:
              TZ: ${TIMEZONE}
              TIMEOUT: 60000
            securityContext:
              runAsUser: 999
              runAsGroup: 999
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 2000Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 5000
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN_INTERNAL}"
        parentRefs:
          - name: envoy-internal
            namespace: networking
    persistence:
      data:
        existingClaim: change-detection
        advancedMounts:
          change-detection:
            app:
              - path: /datastore
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
