---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel-agent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: towonel-agent-secret
    creationPolicy: Owner
    template:
      data:
        TOWONEL_INVITE_TOKEN: "{{ .TOWONEL_INVITE_TOKEN }}"
  dataFrom:
    - extract:
        key: towonel-hub
