router bgp 65000
  bgp router-id 192.168.1.1
  no bgp ebgp-requires-policy

  neighbor k8s peer-group
  neighbor k8s remote-as 65001

  neighbor 192.168.254.81 peer-group k8s
  neighbor 192.168.254.82 peer-group k8s
  neighbor 192.168.254.83 peer-group k8s

  address-family ipv4 unicast
    neighbor k8s next-hop-self
    neighbor k8s soft-reconfiguration inbound
  exit-address-family
exit
